language: node_js
node_js:
  - 11.13.0
deploy:
  - provider: s3
    skip_cleanup: true
    local_dir: build
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "alesya-afanaseva103.com"
    region: us-east-2
    acl: public_read
    on:
      branch: master